const wines = [ { name: 'Airen', code: 'wt0' },
    { name: 'Alicante Henri Bouschet', code: 'wt1' },
    { name: 'Aligote', code: 'wt2' },
    { name: 'Bobal', code: 'wt3' },
    { name: 'Cabernet Franc', code: 'wt4' },
    { name: 'Cabernet Sauvignon', code: 'wt5' },
    { name: 'Cayetana Blanca', code: 'wt6' },
    { name: 'Chardonnay', code: 'wt7' },
    { name: 'Chenin Blanc', code: 'wt8' },
    { name: 'Cot', code: 'wt9' },
    { name: 'Garnacha Tinta', code: 'wt10' },
    { name: 'Grasevina', code: 'wt11' },
    { name: 'Macabeo', code: 'wt12' },
    { name: 'Mazuelo', code: 'wt13' },
    { name: 'Merlot', code: 'wt14' },
    { name: 'Monastrell', code: 'wt15' },
    { name: 'Montepulciano', code: 'wt16' },
    { name: 'Other Red', code: 'wt17' },
    { name: 'Other White', code: 'wt18' },
    { name: 'Pinot Gris', code: 'wt19' },
    { name: 'Pinot Noir', code: 'wt20' },
    { name: 'Riesling', code: 'wt21' },
    { name: 'Rkatsiteli', code: 'wt22' },
    { name: 'Sangiovese', code: 'wt23' },
    { name: 'Sauvignon Blanc', code: 'wt24' },
    { name: 'Syrah', code: 'wt25' },
    { name: 'Tempranillo', code: 'wt26' },
    { name: 'Trebbiano Toscano', code: 'wt27' } ]

    export default wines
